# SwiftLint Configuration for TeamGen
# Simplified and practical iOS development standards

# Directories to exclude from linting
excluded:
  - DerivedData
  - .build
  - TeamGen.xcodeproj
  - Carthage
  - Pods
  - fastlane
  - scripts

# Essential rules only - reduced complexity
opt_in_rules:
  - closure_spacing
  - comma
  - empty_count
  - empty_string
  - first_where
  - force_cast
  - force_try
  - implicit_getter
  - is_disjoint
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - literal_expression_end_indentation
  - mark
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_fallthrough_only
  - no_space_in_method_call
  - notification_center_detachment
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - strong_iboutlet
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message
  - yoda_condition

# Disabled rules
disabled_rules:
  - cyclomatic_complexity # We have complex but well-structured ViewModels
  - function_body_length # Some ViewModels have longer but well-organized methods
  - type_body_length # Design system and comprehensive ViewModels need longer bodies

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1200
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - Row
    - Key
    - ID

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
    - to
    - on
    - at
    - in

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# Custom rules for TeamGen project
custom_rules:
  no_objc_inference:
    name: "No @objc inference"
    regex: "@objc\\s+(?!override)"
    message: "Avoid @objc inference; be explicit about Objective-C exposure"
    severity: warning

  force_https:
    name: "Force HTTPS over HTTP"
    regex: "http://[\\w\\d\\-\\.]+[^\\s]*"
    message: "Use HTTPS URLs instead of HTTP"
    severity: error

  todo_requires_ticket:
    name: "TODO should include ticket reference"
    regex: "TODO(?!.*\\b(?:TODO|FIXME|HACK|BUG|NOTE)\\b)(?!.*#\\d+)"
    message: "TODO comments should include a ticket reference (e.g., TODO: #123)"
    severity: warning

  avoid_print:
    name: "Use logging instead of print"
    regex: "\\bprint\\s*\\("
    message: "Use OSLog instead of print() for production code"
    severity: warning

# Reporter configuration
reporter: "xcode"

# Analyzer rules (for projects using SwiftLint analyzer)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import