# SwiftLint Configuration for TeamGen
# Simplified and practical iOS development standards

# Directories to exclude from linting
excluded:
  - DerivedData
  - .build
  - TeamGen.xcodeproj
  - Carthage
  - Pods
  - fastlane
  - scripts

# Essential rules only - reduced complexity
opt_in_rules:
  - closure_spacing
  - comma
  - empty_count
  - empty_string
  - first_where
  - force_cast
  - force_try
  - implicit_getter
  - is_disjoint
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - trailing_newline
  - trailing_whitespace

# Disabled rules (to reduce noise)
disabled_rules:
  - function_body_length
  - type_body_length
  - file_length
  - large_tuple

# Rule configurations (only for enabled rules)
line_length: 120
identifier_name:
  min_length: 1
  max_length: 60