name: ✨ Feature Request
description: Suggest a new feature for TeamGen
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information about your idea.

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area would this feature affect?
      options:
        - Player Management
        - Team Generation
        - Settings & Configuration
        - UI/UX Improvements
        - Performance & Optimization
        - Data Import/Export
        - Analytics & Reporting
        - Accessibility
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High - Essential for basic usage
        - Medium - Would significantly improve experience
        - Low - Nice to have enhancement
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current pain point?
      placeholder: "As a user, I find it difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Alternatively, we could..."

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe how users would interact with this feature
      placeholder: |
        - As a coach, I want to...
        - As a player, I want to...
        - As a team organizer, I want to...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What defines this feature as "complete"?
      placeholder: |
        - [ ] Users can...
        - [ ] The system should...
        - [ ] Error handling for...

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Small - Minor UI changes or simple logic
        - Medium - New screens or moderate functionality
        - Large - Major feature requiring significant development
        - Extra Large - Complex feature affecting multiple areas
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If you have any visual ideas, screenshots, or mockups, please share them
      placeholder: "You can drag and drop images here..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, examples, or inspiration for this feature
      placeholder: "This feature is inspired by..."

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature aligns with TeamGen's core purpose of team management
          required: true