#!/bin/bash

echo "🔑 API Key Best Practices für Claude Code + GitHub Integration"
echo "============================================================"

echo ""
echo "📋 AKTUELLE SITUATION:"
echo "====================="
echo "1. Claude Code CLI: Nutzt lokalen API Key (Terminal/Environment)"
echo "2. GitHub Actions: Nutzt Repository Secret ANTHROPIC_API_KEY"
echo "3. Mögliche Unterschiede: Ja, können verschiedene Keys sein"
echo ""

echo "🎯 BEST PRACTICE EMPFEHLUNGEN:"
echo "=============================="
echo ""
echo "1. VERSCHIEDENE API KEYS FÜR VERSCHIEDENE UMGEBUNGEN:"
echo "   ✅ Development (Claude Code CLI): Persönlicher API Key"
echo "   ✅ CI/CD (GitHub Actions): Projekt-spezifischer API Key"
echo "   ✅ Production: Separater API Key mit limitierten Permissions"
echo ""

echo "2. WARUM GETRENNTE KEYS?"
echo "   🔒 Sicherheit: Verschiedene Berechtigungen pro Environment"
echo "   📊 Monitoring: Separate Nutzungs-Tracking"
echo "   🚫 Isolation: Persönliche vs. Projekt-Usage"
echo "   💰 Kosten: Separate Billing/Workspace-Zuordnung"
echo ""

echo "3. ANTHROPIC WORKSPACES NUTZEN:"
echo "   📁 Personal Workspace: Für Claude Code CLI"
echo "   🏢 Project Workspace: Für GitHub Actions"
echo "   💼 Organization Workspace: Für Team-Projekte"
echo ""

echo "4. KONKRETE SETUP-EMPFEHLUNG:"
echo "   1. Erstelle separate API Keys:"
echo "      - https://console.anthropic.com/account/keys"
echo "      - 'TeamGen-Development' (für CLI)"
echo "      - 'TeamGen-CI-CD' (für GitHub Actions)"
echo ""
echo "   2. Konfiguriere Umgebungen:"
echo "      - Lokal: export ANTHROPIC_API_KEY='sk-ant-dev-xxx'"
echo "      - GitHub: Repository Secret mit 'sk-ant-cicd-xxx'"
echo ""

echo "5. SICHERHEITS-BEST-PRACTICES:"
echo "   ✅ Verschiedene Keys für verschiedene Zwecke"
echo "   ✅ Regelmäßige Key-Rotation"
echo "   ✅ Monitoring der API-Nutzung"
echo "   ✅ Minimale Berechtigungen pro Key"
echo "   ✅ Sichere Storage (Environment Variables, Secrets)"
echo ""

echo "6. AKTUELLER CHECK:"
echo "   - Lokaler API Key: ${ANTHROPIC_API_KEY:0:12}..."
echo "   - GitHub Secret: Prüfe Repository Settings"
echo "   - Recommendation: Beide Keys sollten unterschiedlich sein"
echo ""

echo "🚨 WICHTIGE SICHERHEITS-PUNKTE:"
echo "==============================="
echo "- NIEMALS API Keys in Code committen"
echo "- IMMER Environment Variables verwenden"
echo "- Verschiedene Keys für verschiedene Environments"
echo "- Regelmäßige Überprüfung der Key-Berechtigungen"
echo "- Monitoring der API-Nutzung und -Kosten"
echo ""

echo "📊 VORTEILE DER TRENNUNG:"
echo "========================"
echo "✅ Sicherheit: Lokaler Kompromiss betrifft nicht CI/CD"
echo "✅ Monitoring: Separate Nutzungsstatistiken"
echo "✅ Kosten: Klare Zuordnung der API-Calls"
echo "✅ Flexibilität: Verschiedene Rate Limits möglich"
echo "✅ Compliance: Bessere Audit-Trails"
echo ""

echo "🔧 SETUP-KOMMANDOS:"
echo "=================="
echo "# 1. Neuen API Key erstellen:"
echo "# https://console.anthropic.com/account/keys"
echo ""
echo "# 2. Lokalen Key setzen:"
echo "export ANTHROPIC_API_KEY='sk-ant-dev-YOUR_DEV_KEY'"
echo ""
echo "# 3. GitHub Secret setzen:"
echo "# https://github.com/JDSavvy/TeamGen/settings/secrets/actions"
echo "# Name: ANTHROPIC_API_KEY"
echo "# Value: sk-ant-cicd-YOUR_CICD_KEY"
echo ""
echo "# 4. Keys in verschiedenen Workspaces organisieren"