#!/bin/bash

echo "🔒 Private Repository @claude Integration Check"
echo "=============================================="

echo "1. PROBLEM DIAGNOSE:"
echo "   📊 Repository: JDSavvy/TeamGen (PRIVAT)"
echo "   🤖 @claude Bot: Benötigt explizite Installation"
echo "   ❌ Aktuell: Keine GitHub App Installation erkannt"
echo ""

echo "2. WARUM @claude NICHT FUNKTIONIERT:"
echo "   - Private Repositories brauchen explizite App-Installation"
echo "   - GitHub Apps haben NICHT automatisch Zugriff auf private Repos"
echo "   - App muss für spezifische Repositories autorisiert werden"
echo ""

echo "3. LÖSUNG - GITHUB APP INSTALLATION:"
echo "   🎯 Schritt 1: App installieren"
echo "      URL: https://github.com/apps/claude"
echo "      Klicke: 'Install'"
echo ""
echo "   🎯 Schritt 2: Repository auswählen"
echo "      Wähle: 'Only select repositories'"
echo "      Selektiere: 'JDSavvy/TeamGen'"
echo ""
echo "   🎯 Schritt 3: Berechtigungen gewähren"
echo "      ✅ Issues (read/write)"
echo "      ✅ Pull requests (read/write)"
echo "      ✅ Contents (read)"
echo "      ✅ Metadata (read)"
echo ""

echo "4. INSTALLATION VERIFIZIEREN:"
echo "   - Gehe zu: https://github.com/settings/installations"
echo "   - Suche: 'Claude' in der Liste"
echo "   - Prüfe: TeamGen ist unter 'Repository access' gelistet"
echo ""

echo "5. AFTER INSTALLATION TEST:"
echo "   - Erstelle Issue: https://github.com/JDSavvy/TeamGen/issues/new"
echo "   - Schreibe: '@claude Hello! Test private repo integration'"
echo "   - Warte: 2-5 Minuten auf Antwort"
echo ""

echo "6. WORKFLOW PERMISSIONS (ZUSÄTZLICH):"
echo "   - Gehe zu: https://github.com/JDSavvy/TeamGen/settings/actions"
echo "   - Aktiviere: 'Allow GitHub Actions to create and approve pull requests'"
echo "   - Wähle: 'Permissive' für Workflow permissions"
echo ""

echo "🚨 WICHTIG:"
echo "=========="
echo "Private Repositories brauchen EXPLIZITE App-Installation!"
echo "Die App sieht dein privates Repo erst nach Installation."
echo ""
echo "Nach Installation sollte @claude in Comments funktionieren! 🚀"